version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: myvault-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myvault
      MYSQL_USER: myvault
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: myvault-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: myvault-backend
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=myvault
      - DB_PASSWORD=password
      - DB_NAME=myvault
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=myvault-secret-key
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: go run cmd/main.go

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myvault-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    command: npm run dev

volumes:
  mysql_data:
  redis_data: